services:
  - name: app
    type: web
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_USER
        value: myuser
      - key: POSTGRES_PASSWORD
        value: mypassword
      - key: POSTGRES_DB
        value: mydatabase
      - key: POSTGRES_HOST
        value: postgres
      - key: DB_PORT
        value: "5432"
    buildCommand: npm install
    autoDeploy: true
    healthCheckPath: /health

databases:
  - name: postgresdb
    plan: starter
  
